# Generated by Django 5.2.17 on 2026-09-09 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_remove_project_annual_opex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payback_period_years', models.FloatField(blank=True, null=True)),
                ('profitability_index', models.FloatField(blank=True, null=True)),
                ('risk_score', models.CharField(default='Medium', max_length=50)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='projects.project')),
            ],
        ),
    ]
