# Generated by Django 5.2.17 on 2026-09-08 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feasibilityproject',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='revenuestream',
            name='project',
        ),
        migrations.RemoveField(
            model_name='opexitem',
            name='project',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='General Feasibility', max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('In Review', 'In Review'), ('Approved', 'Approved')], default='Draft', max_length=20)),
                ('initial_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('discount_rate', models.FloatField(default=10.0, help_text='Discount rate in percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CapexItem',
        ),
        migrations.DeleteModel(
            name='RevenueStream',
        ),
        migrations.DeleteModel(
            name='FeasibilityProject',
        ),
        migrations.DeleteModel(
            name='OpexItem',
        ),
    ]
