# Generated by Django 5.2.17 on 2026-09-09 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_discount_rate_remove_project_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='annual_opex',
        ),
        migrations.RemoveField(
            model_name='project',
            name='annual_revenue',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='payback_period',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('In Review', 'In Review'), ('Approved', 'Approved')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(default='General Feasibility', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='irr',
            field=models.FloatField(blank=True, help_text='Percentage value, e.g., 14.5 for 14.5%', null=True),
        ),
    ]
